export const ERROR = {
    INTERNAL_SERVER_ERROR: "Internal server error",
    USER_NOT_FOUND: "User not found",
    INVALID_PASSWORD: "Invalid password",
    USER_ALREADY_EXISTS: "User already exists",
    INVALID_REQUEST: "Invalid request",
    INVALID_ROUTE: "Invalid route",
    UNAUTHORIZED: "Unauthorized",
    INVALID_TOKEN: "Invalid token",
    TOKEN_NOT_FOUND: "Token not found",
    TOKEN_EXPIRED: "Token expired",
    TOKEN_INVALID: "Token invalid",
    TOKEN_REVOKED: "Token revoked",
    TOKEN_BLACKLISTED: "Token blacklisted",
    INVALID_CREDENTIALS: "Invalid credentials",
    INVALID_EMAIL: "Invalid email",
    INVALID_USERNAME: "Invalid username",
    INVALID_PASSWORD_FORMAT: "Invalid password format",
    INVALID_EMAIL_FORMAT: "Invalid email format",
    INVALID_USERNAME_FORMAT: "Invalid username format",
    INVALID_NAME_FORMAT: "Invalid name format",
    INVALID_PHONE_NUMBER_FORMAT: "Invalid phone number format",
    INVALID_DATE_FORMAT: "Invalid date format"
}