"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    up: async (queryInterface, Sequelize) => {
        const skills = [
            ".net core",
            "Acme",
            "ADO.NET",
            "Adobe XD",
            "Analyze new business domains",
            "Android App Development",
            "Angular",
            "Angular JS",
            "Ansible",
            "Apache",
            "API Testing",
            "ASP.Net core MVC",
            "ASP.Net MVC",
            "ASP.Net Web API",
            "ASP.Net Web Forms",
            "Auto Encoder",
            "AWS",
            "AWS Cloudformation",
            "AWS Lambda GPU",
            "AWS SageMaker",
            "Azure",
            "Azure Cognitive Services",
            "Azure Machine Learning Services",
            "Azure Resource Management Templates",
            "Azure DevOps",
            "Bash",
            "BERT",
            "Bi-LSTM",
            "Bootstrap",
            "Branding",
            "Building Wireframes",
            "Business Domain Expertise",
            "Business Requirement Documentation",
            "C#",
            "ChainerRL",
            "Chef",
            "CNN",
            "Collaboration",
            "Colour Theory",
            "Communication",
            "Comprehend Large Documents",
            "Continuous Delivery",
            "Content Creation (White Papers,Blogs,Articles)",
            "Continuous Integration",
            "Continuous Testing",
            "CoreNLP",
            "CSS",
            "D3.js",
            "Dapper",
            "Dart",
            "Data Cleaning",
            "Data QA",
            "Data Visualization",
            "DataBricks",
            "Datadog",
            "Deep Learning",
            "Design Principles",
            "Django",
            "DjangoRestFramework",
            "Docker",
            "Eclipse",
            "Email Communication",
            "EmberJS",
            "Empathy",
            "Encoder-Decoder",
            "Entity Framework",
            "Entity Framework Core",
            "F#",
            "Fast-CNN",
            "Fast RCNN",
            "fastai",
            "Faster RCNN",
            "fastText",
            "Feature Engineering",
            "Figma",
            "Flask",
            "Flow Charts",
            "Flutter Framework",
            "Focus Groups",
            "Functional Specifications",
            "GCP",
            "gensim",
            "ggplot",
            "Git",
            "Google AI & ML Products",
            "GPT-3",
            "Grid Systems",
            "Groovy",
            "Hibernate",
            "HTML",
            "Hugging Face",
            "Iconography",
            "Identifying User Personas",
            "Imagery",
            "Imutils",
            "IntelliJ",
            "Invision",
            "iOS app development",
            "J Meter",
            "Jasmine",
            "Java",
            "JavaScript",
            "JDBC",
            "Jenkins",
            "JQuery",
            "Jupyter/Colab",
            "Kafka",
            "Karma",
            "Katalon Studio",
            "Keras",
            "KerasRL",
            "KerasRL2",
            "Knockout JS",
            "Kotlin",
            "Kubernetes",
            "Label Systems",
            "Layout",
            "LINQ",
            "Linux Administration",
            "Load Runner",
            "LSTM",
            "Machine Learning",
            "MAME RL",
            "Manual QA",
            "Mask-RCNN",
            "Matplotlib",
            "Maven",
            "Microservices",
            "Mobile & Tablet Design",
            "Mockups",
            "Model Evaluation Metrics",
            "MSTest",
            "MushroomRL",
            "MVC",
            "MySQL",
            "Nagios",
            "Navigation systems",
            "Nginx",
            "NHibernate",
            "nltk",
            "Node.js",
            "NumPy",
            "nUnit",
            "Objective C",
            "OpenAI Baselines",
            "OpenCV",
            "Organization sitemaps",
            "ORM",
            "Pandas",
            "Postgres",
            "Postman",
            "PowerPoint Presentations",
            "Powershell",
            "Presentations",
            "Probability",
            "Process Modeling",
            "Process Optimization",
            "Product Roadmap",
            "Progressive Web Apps",
            "Prospect analysis",
            "Prototyping",
            "Protractor",
            "Puppet",
            "Pyqlearning",
            "Pytessarct",
            "Python",
            "PyTorch",
            "PyTorchCV",
            "R",
            "R-CNN",
            "Rack",
            "Razor view and pages in MVC",
            "React JS",
            "React Native Framework",
            "Responsive Web Design",
            "RL_Coach",
            "RNN",
            "Robot Framework",
            "Ruby",
            "Ruby on Rails",
            "Scikit-Image",
            "scikit-learn",
            "SCM",
            "SCSS",
            "Seaborn",
            "Selenium C#",
            "Selenium Java",
            "Selenium Python",
            "Sequential modelling",
            "Sketch",
            "Soap UI",
            "Spacy",
            "Spark",
            "Spring Boot",
            "Spring MVC",
            "Spring Security",
            "SQL",
            "SSMS",
            "Stable Baselines",
            "Stakeholder Management",
            "Statistics",
            "STS",
            "Styleguides",
            "Swift",
            "Tableau Reporting",
            "Tailwind CSS",
            "Tensorflow",
            "Tensorforce",
            "Terraform",
            "Tomcat",
            "Transformers",
            "Transfer Learning",
            "Typography",
            "UI Elements",
            "UI Patterns",
            "Understand Complex Business Scenarios",
            "Understanding on Databases and Networks",
            "User Flows",
            "User Journey Maps",
            "UX writing",
            "Visual Basic",
            "Verbal Communication",
            "Visual Communication",
            "Visual Studio",
            "VueJS",
            "WCF",
            "Web API",
            "Web Services",
            "Webdriver.io",
            "Windows Administration",
            "Windows Forms",
            "Wireframing",
            "Word Embeddings",
            "WPF",
            "Xamarin app development",
            "xUnit",
            "Yolo",
        ];

        // Bulk insert skills
        await queryInterface.bulkInsert(
            "Skills",
            skills.map((title) => ({
                title,
                createdAt: new Date(),
                updatedAt: new Date(),
            })),
            {}
        );
    },

    down: async (queryInterface, Sequelize) => {
        await queryInterface.bulkDelete("Skills", null, {});
    },
};
